version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-collection"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jcwshswn4ol2"
s3_prefix = "image-collection"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
